### ISSUE TITLE
Misunderstand parameters,"os_KNN"

### ISSUE THREAD

**Issue by Jandsome** [CityU-AIM-Group/SOMA#10]
Wonderful Works !
I have some doubts about the Top-K proposed in your paper,does this K stand for classes here?But I noticed that you set os_KNN to 5 in the config file soma_aood_pascal_to_clipart_r50 , But in this task ,there has 12 known classes .
Could you please explain to me what os_KNN stands for here?
![image](https://github.com/user-attachments/assets/660003d4-18b5-490f-b9ca-bffca273a803)

**Comment by wymanCV** [comment]
Hi, thank you for your interest in our work! K is not the class number. K is a hyper-parameter controlling how many triplets (i.e., motifs in the paper) are used to generate the open-set loss for each image. The role of K is similar to OW-DETR [1], which selects K potential unknown object queries. The main difference of our method is that it lifts the object query to motif, i.e., a combination of multiple object queries. Hope this will help!

OW-DETR: Open-world Detection Transformer [1]

**Comment by Jandsome** [comment]
Thanks a lot for your kind detailed explanation，wish you a good day!
