### ISSUE TITLE
I got a problem when I try to train the model.

### ISSUE THREAD

**Issue by lyhmay** [CityU-AIM-Group/SOMA#2]
I want to train the model on 1 rtx4090.
and I enter:
**GPUS_PER_NODE=1 
./tools/run_dist_launch.sh 1 python main.py --config_file ./configs/soma_aood_city_to_foggy_r50.yaml --opts DATASET.AOOD_SETTING 1**

 but I got:

  **File "SOMA/datasets/data_prefetcher.py", line 22, in __init__
    self.preload()
  File "SOMA/datasets/data_prefetcher.py", line 29, in preload
    self.next_samples, self.next_targets = next(self.loader)
ValueError: too many values to unpack (expected 2)**

and I found the type of next(self.loader) is list which length is 3
and the type of content is
**<class 'util.misc.NestedTensor'> <class 'list'> <class 'list'>**
Could you please tell me how can I solve it ?

**Comment by wymanCV** [comment]
Hi, thank you for your interest! 

I just corrected the training script in Readme, and sorry for this small mistake. You should use `main_multi_eval `  as shown in [run.sh](https://github.com/CityU-AIM-Group/SOMA/blob/main/run.sh)

`#GPUS_PER_NODE=1 MASTER_PORT=21001 ./tools/run_dist_launch.sh 1 python main_multi_eval.py --config_file configs/soma_aood_city_to_bdd100k_r50.yaml --opts DATASET.AOOD_SETTING 1`

I haven't met your issue. Some information about the dataloader is listed below for your reference:
https://github.com/CityU-AIM-Group/SOMA/blob/9950cb67fe6eb21bea78ce9d96d836f41298fb90/engine_aood.py#L39

`print(next(iter(data_loader))[0].decompose()[0].shape)`
torch.Size([4, 3, 704, 1251]) (4 images: 2 for source and 2 for target)


`print(len(next(iter(data_loader))[1]))`
2 (labels for 2 source images)

`print(len(next(iter(data_loader))))`
2 (nestedTensor and labels )


Moreover, a single GPU may not be suitable for a Deformable DETR baseline (I haven't tried this), and you may need to change the batch size. Thanks

https://github.com/encounter1997/SFA/issues/4

**Comment by lyhmay** [comment]
I appreciate your timely response and the support you provided. 
Thanks to your help, I have resolved the issue.
Best wishes!

**Comment by wymanCV** [comment]
I am so so so sorry for the big mistake I made when I cleaned my code, which will lead to significantly different results with our paper. I just noticed that due to an issue in terms of the reproducibility. I have updated the code and told the reason in ReadMe. I'm very sorry for wasting your energy because of my mistake.

**Comment by stz-source** [comment]
> 感谢您及时的回复和提供的支持。 感谢您的帮助，我已解决了这个问题。 祝一切顺利！

请问你是如何修改的，我也遇到了类似的问题
