### ISSUE TITLE
About Experimental Metrics

### ISSUE THREAD

**Issue by lyhmay** [CityU-AIM-Group/SOMA#3]
I following the referred conda   environment and trained on two v100 GPU。But the results I got is not very good:
 **Cityscape -> Cityscape foggy** 
I run 
```
GPUS_PER_NODE=2
 CUDA_VISIBLE_DEVICES=2,3 ./tools/run_dist_launch.sh 2 python main_multi_eval.py --config_file /media/vipsl-1/lyh_py_code/projects/SOMA/configs/soma_aood_city_to_foggy_r50.yaml --opts DATASET.AOOD_SETTING 1 OUTPUT_DIR experiments/city_to_foggy/setting1
```
I got :
car has 12710 predictions.
truck has 2545 predictions.
bus has 1931 predictions.
unknown has 32014 predictions.
{'detection_mAP50: ': 30.63516616821289, 'Absolute OSE (total_num_unk_det_as_known): ': '{50: 111.0}', 'total_num_unk: ': '5079', 'base_mAP: ': 40.82, 'AP50: ': "['57.5', '24.5', '40.5', '0.1']", 'Recall50: ': "['64.2', '42.4', '61.9', '3.7']", 'Unknown AP50: ': 'tensor(0.0653)', 'Unknown Recall50: ': '3.681827131325064', 'ap_map_wi_aose_ar': '57.49 & 24.51 & 40.47 & 40.82 & 0.667 & 111.0 & 3.68 & 0.07', 'report_results': ['40.82', '3.68', '0.667', '111'], 'title': 'car & truck & bus & mAP_base & WI_08 & AOSE & Recall_novel & nodel_AP50'}
Training time 9:39:25

**Setting 2 Result:**
person has 14445 predictions.
bicycle has 7549 predictions.
bus has 1625 predictions.
unknown has 25581 predictions.
{'detection_mAP50: ': 28.055559158325195, 'Absolute OSE (total_num_unk_det_as_known): ': '{50: 842.0}', 'total_num_unk: ': '5302', 'base_mAP: ': 37.22, 'AP50: ': "['43.3', '38.0', '30.4', '0.6']", 'Recall50: ': "['53.7', '54.5', '40.2', '10.6']", 'Unknown AP50: ': 'tensor(0.5664)', 'Unknown Recall50: ': '10.61863447755564', 'ap_map_wi_aose_ar': '43.26 & 37.98 & 30.41 & 37.22 & 3.581 & 842.0 & 10.62 & 0.57', 'report_results': ['37.22', '10.62', '3.581', '842'], 'title': 'person & bicycle & bus & mAP_base & WI_08 & AOSE & Recall_novel & nodel_AP50'}
Training time 9:46:23

**Pascal to clipart**

{'detection_mAP50: ': 18.894052505493164, 'Absolute OSE (total_num_unk_det_as_known): ': '{50: 6321.0}', 'total_num_unk: ': '1882', 'base_mAP: ': 20.34, 'AP50: ': "['19.7', '28.1', '18.4', '19.4', '14.8', '35.2', '20.4', '13.1', '27.4', '6.8', '4.5']", 'Recall50: ': "['67.1', '66.7', '33.2', '48.1', '38.0', '90.5', '53.5', '30.0', '71.2', '47.8', '39.5']", 'Unknown AP50: ': 'tensor(4.4737)', 'Unknown Recall50: ': '39.53241232731137', 'ap_map_wi_aose_ar': '19.74 & 28.14 & 18.42 & 19.38 & 14.81 & 35.19 & 20.37 & 13.14 & 27.35 & 6.81 & 20.34 & 9.151 & 6321.0 & 39.53 & 4.47', 'report_results': ['20.34', '39.53', '9.151', '6321'], 'title': 'aeroplane & bicycle & bird & boat & bottle & bus & car & cat & chair & cow & mAP_base & WI_08 & AOSE & Recall_novel & nodel_AP50'}
Training time 9:21:16

Where did it go wrong?

**Comment by wymanCV** [comment]
Hi, thanks for reproducing our work!

You can refer to the generated "eval_results.txt" file in OUTPUT_DIR, which saves the evaluation results for each training epoch in latex format.  The best model is usually selected in the final ten epochs instead of the final epoch.

 I think that the results for your first experiments are close to ours, e.g., Unk AR 3.68 (yours) with 4.08 (reported). The small gap is common if you directly select the final model due to the randomness. Besides, in DA, training too long sometimes also causes some performance decrease.

**Comment by lyhmay** [comment]
Thank you for your response. I apologize for not finding the column names in "eval_results.txt" and instead referring to the final training log. I will further examine the results in detail. Once again, I appreciate your assistance. By the way, is my training time of approximately 9 hours longer than yours?

**Comment by wymanCV** [comment]
I think your experiment is correct. The results generation process is achieved here:

https://github.com/CityU-AIM-Group/SOMA/blob/458205a003d61798dd507d2677c32247a88b1b35/main_multi_eval.py#L283

**Comment by lyhmay** [comment]
Thank you for your response. I will carefully read your article. Your code is excellent and has provided me with many insights.

**Comment by wymanCV** [comment]
Happy to hear that. Hope our work will be helpful for your research.

**Comment by wymanCV** [comment]
I am so so so sorry for the big mistake I made when I cleaned my code, which will lead to significantly different results with our paper. I just noticed that due to an issue in terms of the reproducibility. I have updated the code and told the reason in ReadMe. I'm very sorry for wasting your energy because of my mistake.

@lyhmay
