### ISSUE TITLE
May I ask if it is possible to publish Well trained models

### ISSUE THREAD

**Issue by Luhui-Zhao** [CityU-AIM-Group/SOMA#4]
Hello, I am very interested in your paper. Thank you very much for the methods in your paper. Recently, I have been reproducing the code in your paper, but my reproducing results differ by 10 percentage points from those in your paper.I am using three 3090 graphics cards. Could you please publish Well trained models? Thank you very much for your help.The experiment I ran was Cityscapes → Foggy Cityscapes:het-sem
[Epoch 60] [Task 0]57.91 & 34.87 & 28.07 & 40.28 & 0.631 & 29.0 & 4.17 & 0.07
[Epoch 60] [Task 1]59.21 & 32.09 & 34.7 & 42.0 & 0.741 & 59.0 & 4.12 & 0.08
[Epoch 60] [Task 2]56.99 & 26.08 & 34.07 & 39.05 & 0.95 & 154.0 & 3.47 & 0.09
Epoch 60: 40.28 & 4.17 & 0.631 & 29 & 42.0 & 4.12 & 0.741 & 59 & 39.05 & 3.47 & 0.95 & 154

[Epoch 61] [Task 0]57.65 & 35.57 & 28.55 & 40.59 & 0.393 & 24.0 & 3.09 & 0.05
[Epoch 61] [Task 1]58.56 & 32.79 & 38.23 & 43.19 & 0.615 & 51.0 & 3.35 & 0.06
[Epoch 61] [Task 2]56.78 & 26.64 & 34.94 & 39.45 & 0.822 & 135.0 & 3.11 & 0.07
Epoch 61: 40.59 & 3.09 & 0.393 & 24 & 43.19 & 3.35 & 0.615 & 51 & 39.45 & 3.11 & 0.822 & 135

[Epoch 62] [Task 0]58.16 & 30.67 & 29.72 & 39.52 & 0.531 & 29.0 & 3.45 & 0.06
[Epoch 62] [Task 1]58.83 & 27.65 & 37.61 & 41.36 & 0.72 & 59.0 & 3.73 & 0.08
[Epoch 62] [Task 2]56.74 & 23.65 & 35.46 & 38.62 & 0.829 & 135.0 & 3.29 & 0.08
Epoch 62: 39.52 & 3.45 & 0.531 & 29 & 41.36 & 3.73 & 0.72 & 59 & 38.62 & 3.29 & 0.829 & 135

[Epoch 63] [Task 0]57.61 & 36.81 & 30.04 & 41.49 & 0.508 & 23.0 & 2.36 & 0.06
[Epoch 63] [Task 1]58.75 & 32.49 & 37.36 & 42.87 & 0.643 & 49.0 & 3.41 & 0.07
[Epoch 63] [Task 2]57.09 & 27.01 & 36.12 & 40.07 & 0.879 & 141.0 & 3.47 & 0.08
Epoch 63: 41.49 & 2.36 & 0.508 & 23 & 42.87 & 3.41 & 0.643 & 49 & 40.07 & 3.47 & 0.879 & 141

[Epoch 64] [Task 0]58.04 & 34.6 & 29.64 & 40.76 & 0.505 & 26.0 & 3.45 & 0.06
[Epoch 64] [Task 1]59.25 & 33.25 & 37.61 & 43.37 & 0.638 & 49.0 & 3.48 & 0.07
[Epoch 64] [Task 2]57.02 & 25.13 & 35.2 & 39.12 & 0.988 & 149.0 & 3.54 & 0.09
Epoch 64: 40.76 & 3.45 & 0.505 & 26 & 43.37 & 3.48 & 0.638 & 49 & 39.12 & 3.54 & 0.988 & 149

**Comment by wymanCV** [comment]
Hi, thanks for your interest in our work. Could you please try using 2 GPUs for training, which should obtain similar (or better) results than the reported ones? Thanks. I will provide our trained models in the near future.

**Comment by Luhui-Zhao** [comment]
> Hi, thanks for your interest in our work. Could you please try using 2 GPUs for training, which should obtain similar (or better) results than the reported ones? Thanks. I will provide our trained models in the near future.

Thank you very much for receiving your reply. Today, I used two 3090 graphics cards to train the model. The indicators finally obtained are as follows, and there is still a big gap between them and those in your paper.Thank you very much for your help.The experiment I ran was Cityscapes → Foggy Cityscapes:het-sem
[Epoch 58] [Task 0]59.35 & 37.49 & 45.07 & 47.3 & 0.666 & 37.0 & 3.27 & 0.04
[Epoch 58] [Task 1]59.97 & 31.98 & 43.29 & 45.08 & 0.769 & 69.0 & 3.99 & 0.05
[Epoch 58] [Task 2]57.99 & 24.12 & 41.85 & 41.32 & 0.87 & 161.0 & 3.74 & 0.07
Epoch 58: 47.3 & 3.27 & 0.666 & 37 & 45.08 & 3.99 & 0.769 & 69 & 41.32 & 3.74 & 0.87 & 161

[Epoch 59] [Task 0]59.42 & 36.37 & 48.0 & 47.93 & 0.598 & 31.0 & 3.09 & 0.04
[Epoch 59] [Task 1]60.24 & 31.95 & 46.23 & 46.14 & 0.653 & 56.0 & 3.67 & 0.05
[Epoch 59] [Task 2]58.26 & 22.83 & 42.59 & 41.23 & 0.876 & 156.0 & 3.41 & 0.07
Epoch 59: 47.93 & 3.09 & 0.598 & 31 & 46.14 & 3.67 & 0.653 & 56 & 41.23 & 3.41 & 0.876 & 156

[Epoch 60] [Task 0]59.1 & 36.32 & 43.13 & 46.18 & 0.699 & 37.0 & 3.09 & 0.04
[Epoch 60] [Task 1]59.88 & 33.22 & 43.56 & 45.55 & 0.813 & 71.0 & 3.48 & 0.06
[Epoch 60] [Task 2]57.9 & 24.67 & 41.55 & 41.37 & 0.902 & 166.0 & 3.33 & 0.07
Epoch 60: 46.18 & 3.09 & 0.699 & 37 & 45.55 & 3.48 & 0.813 & 71 & 41.37 & 3.33 & 0.902 & 166

[Epoch 61] [Task 0]58.99 & 34.8 & 44.46 & 46.08 & 0.556 & 32.0 & 3.09 & 0.04
[Epoch 61] [Task 1]59.79 & 30.55 & 42.61 & 44.32 & 0.697 & 63.0 & 3.73 & 0.06
[Epoch 61] [Task 2]57.85 & 23.23 & 41.77 & 40.95 & 0.828 & 150.0 & 3.39 & 0.07
Epoch 61: 46.08 & 3.09 & 0.556 & 32 & 44.32 & 3.73 & 0.697 & 63 & 40.95 & 3.39 & 0.828 & 150

[Epoch 62] [Task 0]59.32 & 36.56 & 39.39 & 45.09 & 0.624 & 32.0 & 2.72 & 0.04
[Epoch 62] [Task 1]59.91 & 30.75 & 40.37 & 43.68 & 0.715 & 58.0 & 3.54 & 0.05
[Epoch 62] [Task 2]57.98 & 23.42 & 40.22 & 40.54 & 0.822 & 142.0 & 3.31 & 0.07
Epoch 62: 45.09 & 2.72 & 0.624 & 32 & 43.68 & 3.54 & 0.715 & 58 & 40.54 & 3.31 & 0.822 & 142

[Epoch 63] [Task 0]59.45 & 34.97 & 41.92 & 45.45 & 0.661 & 34.0 & 2.9 & 0.04
[Epoch 63] [Task 1]60.04 & 30.59 & 42.97 & 44.53 & 0.774 & 64.0 & 3.61 & 0.06
[Epoch 63] [Task 2]58.1 & 24.09 & 41.83 & 41.34 & 0.895 & 152.0 & 3.5 & 0.07
Epoch 63: 45.45 & 2.9 & 0.661 & 34 & 44.53 & 3.61 & 0.774 & 64 & 41.34 & 3.5 & 0.895 & 152

[Epoch 64] [Task 0]59.44 & 34.64 & 41.47 & 45.18 & 0.62 & 36.0 & 3.09 & 0.04
[Epoch 64] [Task 1]60.06 & 30.55 & 43.13 & 44.58 & 0.767 & 68.0 & 3.54 & 0.06
[Epoch 64] [Task 2]58.07 & 22.87 & 42.5 & 41.15 & 0.901 & 163.0 & 3.29 & 0.07
Epoch 64: 45.18 & 3.09 & 0.62 & 36 & 44.58 & 3.54 & 0.767 & 68 & 41.15 & 3.29 & 0.901 & 163

**Comment by wymanCV** [comment]
Hi, thank you so much for reproducing our method! Pls don't change the batch size. 

I have uploaded the training log of my reproduced experiments for the open-sourced version on the C2F het-sem setting [onedrive](https://portland-my.sharepoint.com/:f:/g/personal/wuyangli2-c_my_cityu_edu_hk/Eprave-0XYNAiDEUP-D4egkBjpwvhw75ZXSDjruYMCvkBA?e=xeypQS), which can achieve better performance (epoch 51) than our reported ones. The original experiments consistent with the paper are on the other server and I don't have access recently.

Moreover, I also noticed that in your experiments, some metrics are better than our reported ones (your AOSE at epoch 59 is 31, which is better than our 139) while some are worse (47.93 mAP_b vs 50mAP_b).  I am not sure whether it is caused by the randomness. Maybe you can try to run more times.

**Comment by Luhui-Zhao** [comment]
> Hi, thank you so much for reproducing our method! Pls don't change the batch size.
> 
> I have uploaded the training log of my reproduced experiments for the open-sourced version on the C2F het-sem setting [onedrive](https://portland-my.sharepoint.com/:f:/g/personal/wuyangli2-c_my_cityu_edu_hk/Eprave-0XYNAiDEUP-D4egkBjpwvhw75ZXSDjruYMCvkBA?e=xeypQS), which can achieve better performance (epoch 51) than our reported ones. The original experiments consistent with the paper are on the other server and I don't have access recently.
> 
> Moreover, I also noticed that in your experiments, some metrics are better than our reported ones (your AOSE at epoch 59 is 31, which is better than our 139) while some are worse (47.93 mAP_b vs 50mAP_b). I am not sure whether it is caused by the randomness. Maybe you can try to run more times.

Thank you very much for your reply again. Next, I will explore it by myself. Thank you very much for your code and ideal provided in the paper.

**Comment by wymanCV** [comment]
Thank you so so much for your issue!!!

I am so so so sorry for the big mistake I made when I cleaned my code, which will lead to significantly different results with our paper. I just noticed that due to an issue in terms of the reproducibility. I have updated the code and told the reason in ReadMe. I'm very sorry for wasting your energy because of my mistake.
