### ISSUE TITLE
Train error after corrections in DAOD.py

### ISSUE THREAD

**Issue by Jandsome** [CityU-AIM-Group/SOMA#6]
Hi, Excellent works!  
Something was wrong when I was training this week. I guess it's because you corrected the DAOD.py three weeks ago . I found you corrected  in line 155 two times, but the second time you changed the first correction back.  I don't konw why.  
And in line 45 you changed                                                                      
 'val_data_list': root / 'Cityscapes/AOOD_Main/val_target.txt'   
to 
 'val_data_list': root / 'Cityscapes/AOOD_Main/train_target.txt'
I wonder whether it's  appropriate  if train_data_list is same to val_data_list.
And The error comes to me is
FileNotFoundError: [Errno 2] No such file or directory: '/data/jyq/SOMA/datasets/dataset/Cityscapes/leftImg8bit_foggy/val/jena/jena_000061_000019_leftImg8bit_foggy_beta_0.02.png'
FileNotFoundError: [Errno 2] No such file or directory: '/data/jyq/SOMA/datasets/dataset/Cityscapes/leftImg8bit_foggy/val/hamburg/hamburg_000000_029144_leftImg8bit_foggy_beta_0.02.png'

However,it didn't  happen before you made thess corrections, it will be so kind of you to help me solve this issue.
Thank you!

**Comment by wymanCV** [comment]
Hi, thank you for your attention! I just corrected the image folder of the dataset, which I think should work now.

https://github.com/CityU-AIM-Group/SOMA/blob/08182aec101abac275cbad857e1c9fca894bbe13/datasets/DAOD.py#L39

Using the same unlabeled target-domain dataset for training and test is reasonable for some existing DAOD benchmarks, e.g., P2C.  See here from the first work: Strong-Weak Distribution Alignment for Adaptive Object Detection
<img width="281" alt="image" src="https://github.com/CityU-AIM-Group/SOMA/assets/93365573/e3e18053-3b00-4d10-974e-2e344296050f">



The reason we didn't use the val set for Cityscapes is that it only contains 500 images with very limited open-set objects, which are insufficient for some open-set detection metrics, e.g., AOSE., and the number of AOSE will be very very small and unstable.

**Comment by Jandsome** [comment]
thanks a lot ,I think it will be work  after you correct in line 39
