### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Lybnn** [CityU-AIM-Group/SOMA#7]
Hi author, after I run to Epoch: [9] I have a problem: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: please tell me how I should modify it!
![图片1](https://github.com/CityU-AIM-Group/SOMA/assets/67939175/e19ae32f-2909-4473-b6a7-89e526b625f8)

**Comment by wymanCV** [comment]
Hi, thanks for your interest!

May I know your pytorch version?

**Comment by Lybnn** [comment]
Thank you for your reply. My pytorch is 1.9.0 and Cuda is 11.1. the following is all my environment configuration.
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
ca-certificates           2023.12.12           h06a4308_0    defaults
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cython                    3.0.9                    pypi_0    pypi
fonttools                 4.49.0                   pypi_0    pypi
importlib-resources       6.1.3                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
matplotlib                3.7.5                    pypi_0    pypi
multiscaledeformableattention 1.0                      pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    defaults
numpy                     1.24.4                   pypi_0    pypi
openssl                   3.0.13               h7f8727e_0    defaults
packaging                 24.0                     pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py38h06a4308_0    defaults
pycocotools               2.0.7                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.8.18               h955ad1f_0    defaults
python-dateutil           2.9.0.post0              pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    defaults
scipy                     1.10.1                   pypi_0    pypi
setuptools                68.2.2           py38h06a4308_0    defaults
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
torch                     1.9.0+cu111              pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
tqdm                      4.66.2                   pypi_0    pypi
typing-extensions         4.10.0                   pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0    defaults
xz                        5.4.6                h5eee18b_0    defaults
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults

**Comment by Lybnn** [comment]
Thank you for your reply. My pytorch is 1.9.0 and Cuda is 11.1. the following is all my environment configuration.
![image](https://github.com/CityU-AIM-Group/SOMA/assets/67939175/73318183-6b42-4a6c-83e2-fc7a4f32b799)

**Comment by wymanCV** [comment]
Hi, maybe you can try to downgrade the Pytorch version to 1.5.1 or more early. Actually, as I have checked with someone else who ran our code successfully, I think that the core reason is the environment, especially for the pytorch version. Please have a try. Thanks!

**Comment by Lybnn** [comment]
Thank you very much for answering the questions!I will change the pytorch environment to try it out!Thanks！

**Comment by xuchanghua-88** [comment]
I met the same problem as you, Do you solve it already? If you do, please tell me the detail. Thank you!
