### ISSUE TITLE
Could you please tell me the Numerical implication in eval_result.py

### ISSUE THREAD

**Issue by Jandsome** [CityU-AIM-Group/SOMA#8]
Wonderful work!  
I really don't know the Numerical implication in eval_result.py. In my opinion,Tasks 0, 1, and 2 should represent three, four, and five cases of the new class, respectively.But I don't understand the meaning of these numerical value in the following picture.

![QQ截图20240603161405](https://github.com/CityU-AIM-Group/SOMA/assets/125888145/fd412eb0-6579-477d-b758-22766e603b20)
Could you please tell me what's the meaning of these Numerical implication respectively. 
It will be so kind of you to tell me the correspondence between the data and the experiment chart

**Comment by wymanCV** [comment]
Thank you so much for your interest! Please refer to the following figure with my notes. Task0-2 indicates Task1-3 in the paper.

![Picture1](https://github.com/CityU-AIM-Group/SOMA/assets/93365573/6397e0f7-a1a1-4dba-8b53-06e39b0b6be6)

**Comment by Jandsome** [comment]
Thanks a lot for your kind detailed explanation，I still have one last question 

here is what I get:
setting 1  -> het-sem
setting 2  -> hom-sem
setting 3  -> freq-dec
setting 2  ->freq-inc
Am I right? Thank you again for your kindness!

**Comment by wymanCV** [comment]
Yes, you are right, except for the typo error "setting4  ->freq-inc".

**Comment by Jandsome** [comment]
Thanks a lot for your kind detailed explanation，wish you a good day!
